### PR TITLE
We have a name!

### LINKED ISSUE #19: We need a new name
Because "De novo scilife" is a silly name for any piece of software. Any suggestions?

### PR DESCRIPTION
**Pull request by remiolsen**
- [x] Merge pull request
- [x] Rename GH repository

closes #19

### CODE REVIEW

**Comment by vezzi** [comment]
SUper cool!!!!!

**Comment by guillermo-carrasco** [comment]
NouGAT in catalan means "New cat" xD :cat: funny

**Comment by remiolsen** [comment]
Awesome! That makes makes me happier with the choice :joy_cat:

**Comment by guillermo-carrasco** [comment]
[Sweet](http://en.wikipedia.org/wiki/Nougat)

**Pull request merged**
